export const ep_token = '/.netlify/functions/token'
export const ep_search = '/.netlify/functions/search'
export const ep_searchById = '/.netlify/functions/searchByID'
export const ep_game = '/.netlify/functions/game'
export const ep_franchises = '/.netlify/functions/franchises'
